# multiple message types
on:
  telegram_bot:
    event:
      - photo
      - text
    token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    webhook: true
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          telegram_text: ${{ on.telegram_bot.outputs.text }}
        run: |
          echo telegram text: $telegram_text

  add_file:
    name: add file
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add file 123
        run: echo "123" > ./file.txt
     
      - run: git --version
      
      - uses: actions/checkout@v2
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push  

  #    - uses: stefanzweifel/git-auto-commit-action@v4
  #      with:
  #        commit_message: experimen
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        COMMIT_MESSAGE: "hello"
  #        COMMIT_AUTHOR_NAME: "CS Fixer"
  #        COMMIT_AUTHOR_EMAIL: "john.doe@example.com"
 #     - name: add and commit
 #       uses: EndBug/add-and-commit@v5
 #       with:
 #         message: "Add the very useful text file"
 #         add: "*.txt --force"
 #         author_name: Bot
 #         author_email: bot1@example.com        
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
