# multiple message types
on:
  telegram_bot:
    event:
      - photo
      - text
    token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    webhook: true
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          telegram_text: ${{ on.telegram_bot.outputs.text }}
        run: |
          echo telegram text: $telegram_text
     
  add_file_all:
    name: add file
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - name: everything
        uses: actions/checkout@v2
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ./repo-folder
          cd repo-folder
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          echo "12ggggg3234234" > ./file.txt
          pwd
          ls -la
          git add ./file.txt
          git commit -m "Add changes !!!"
          git status
          git log
          ls -la
          git show-ref
          cat ./workflows/rss.yml
          git push origin main        

#  add_file:
#    name: add file
#    runs-on: ubuntu-latest
#    container: node:10.16-jessie
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2

#      - name: add file 123
#        run: echo "123hljslfsjdfljk" > ./file.txt
     
#      - run: git --version
      
#      - name: Commit files
#        uses: actions/checkout@v2
#        run: |
#          git config --local user.email "test@github.com"
#          git config --local user.name "GitHub Action test"
#          git remote show origin
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#          git remote show origin
#          git add ./file.txt
#          git commit -m "Add changes"
#          git status
#          git log
#ls
#          git push origin master

          
#      - name: Push changes # push the output folder to your repo
#        uses: ad-m/github-push-action@master
#        with:
#          # branch: B77 #ignore if your branch is master
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          force: true      
      
#      - uses: actions/checkout@v2
#        run: |
#          date > generated.txt
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "generated"
#          git push  

  #    - uses: stefanzweifel/git-auto-commit-action@v4
  #      with:
  #        commit_message: experimen
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #        COMMIT_MESSAGE: "hello"
  #        COMMIT_AUTHOR_NAME: "CS Fixer"
  #        COMMIT_AUTHOR_EMAIL: "john.doe@example.com"
 #     - name: add and commit
 #       uses: EndBug/add-and-commit@v5
 #       with:
 #         message: "Add the very useful text file"
 #         add: "*.txt --force"
 #         author_name: Bot
 #         author_email: bot1@example.com        
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
